bookers2_789d/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "homes#top"
  get "home/about"=>"homes#about"
  get 'search' => 'searches#search'
  get "tag_searches/search" => "tagsearches/search"
  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites,only: [:create,:destroy]
    resources :book_comments, only: [:create,:destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships,only: [:create,:destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

bookers2_789d/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2_789d/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorite, dependent: :destroy
  
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  validates :category,presence:true
  
  def favorited_by?(user)
    favorite.exists?(user_id: user.id)
  end
  
  def self.looks(search,word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?", "#{word}")
    elsif search == "forword_match"
      @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?", "%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?", "%#{word}%")
    else
      @book = Book.all
    end
  end
  
  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :star_count, -> {order(star: :desc)}
  

end

bookers2_789d/app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

bookers2_789d/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

bookers2_789d/app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to:follower, class_name: "User"
  belongs_to:followed, class_name: "User"
end

bookers2_789d/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :name, presence: true
  validates :introduction, length: { maximum: 50 }



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  def self.looks(search,word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end
end

bookers2_789d/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except:[:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

bookers2_789d/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_maching_login_user,only:[:edit,:update]

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = User.find(@book.user_id)
    @book_comment = BookComment.new
  end

  def index
    if params[:latest]
      @books = Book.latest
    elsif params[:old]
      @books = Book.old
    elsif params[:star_count]
      @books = Book.star_count
    else
      @books = Book.all
    end

    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "You have destroyed book successfully."
  end


  private

  def book_params
    params.require(:book).permit(:title,:body,:image,:star,:category)
  end

  def is_maching_login_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

bookers2_789d/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

bookers2_789d/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

bookers2_789d/app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search],params[:word])
    else
      @books = Book.looks(params[:search],params[:word])
    end
    render "/layouts/search_result"

  end
end

bookers2_789d/app/controllers/tag_searches_controller.rb
class TagSearchesController < ApplicationController

  def search
    @model = Book
    @word = params[:content]
    @books = Book.where("category LIKE?","%#{@word}%")
    render "tag_searches/search"
  end
end

bookers2_789d/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update,:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end
  

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

bookers2_789d/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2_789d/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

bookers2_789d/app/helpers/books_helper.rb
module BooksHelper
end

bookers2_789d/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2_789d/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2_789d/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

bookers2_789d/app/helpers/seaches_helper.rb
module SeachesHelper
end

bookers2_789d/app/helpers/tag_searches_helper.rb
module TagSearchesHelper
end

bookers2_789d/app/helpers/users_helper.rb
module UsersHelper
end

bookers2_789d/app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

bookers2_789d/app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

bookers2_789d/app/views/tag_searches/_tagsearch.html.erb
<% if user_signed_in? %>
  <div class="container">
    <div class="row m-2">
      <div class="col-md-5 mx-auto">
        <div class="search_form">
          <%= form_with url: tag_searches_search_path, method: :get do |f| %>
            <%= f.text_field :content %>
            <%= f.submit 'タグ検索', class:"btn btn-info" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

bookers2_789d/app/views/tag_searches/search.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4>Books search for"<%= @word %>"</h4>
      <table class="table">
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th>Tag</th>
          <th colspan="3"></th>
        </tr>
        <% @books.each do |book| %>
          <tr>
            <td><%= image_tag book.user.get_profile_image, size:"60x60" %></td>
            <td><%= link_to book.title %></td>
            <td><%= book.body %></td>
            <td><%= link_to book.category %></td>
            <td class="favorite_btn_<%= book.id %>">
              <%= render "favorites/favorite-btn", book: book %>
            </td>
            <td><%= book.book_comments.count %></td>
            <td><%= render 'books/static_rate', book: book %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>