bookers2_789a/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "homes#top"
  get "home/about"=>"homes#about"
  get 'search' => 'searches#search'
  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites,only: [:create,:destroy]
    resources :book_comments, only: [:create,:destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships,only: [:create,:destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :rooms, only: [:create,:show]
  resources :messages, only: [:create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

bookers2_789a/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorite, dependent: :destroy
  has_many :favorited_users, through: :favorite, source: :user
  has_many :read_counts, dependent: :destroy

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorite.exists?(user_id: user.id)
  end

  def self.looks(search,word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?", "#{word}")
    elsif search == "forword_match"
      @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?", "%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?", "%#{word}%")
    else
      @book = Book.all
    end
  end


end

bookers2_789a/app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

bookers2_789a/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

bookers2_789a/app/models/read_count.rb
class ReadCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

bookers2_789a/app/models/room.rb
class Room < ApplicationRecord
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

bookers2_789a/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorite, source: :book
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :read_counts, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :name, presence: true
  validates :introduction, length: { maximum: 50 }



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.looks(search,word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end
end

bookers2_789a/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_maching_login_user,only:[:edit,:update]

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = User.find(@book.user_id)
    @book_comment = BookComment.new
    if @book.user_id != current_user.id
      current_user.read_counts.create(book_id: @book.id)
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @high_scores = Book.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "You have destroyed book successfully."
  end


  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

  def is_maching_login_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

bookers2_789a/app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    if Entry.where(:user_id =>current_user.id, :room_id => params[:message][:room_id]).present?
      @message = Message.create(params.require(:message).permit(:message, :user_id, :content, :room_id).merge(:user_id => current_user.id))
    else
      flash[:alert] = "メッセージ送信に失敗しました。"
    end
    redirect_to "/rooms/#{@message.room_id}"
  end
end

bookers2_789a/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :authenticate_user!

  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

bookers2_789a/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update,:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new

    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

bookers2_789a/app/helpers/messages_helper.rb
module MessagesHelper
end

bookers2_789a/app/helpers/rooms_helper.rb
module RoomsHelper
end

bookers2_789a/app/views/books/index.html.erb
<%= render 'layouts/errors', obj: @book %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="4"></th>
          </tr>
        </thead>
        <tbody>
          <% @high_scores.each do |book| %>
            <tr>
              <td><%= link_to(book.user) do %>
                <%= image_tag book.user.get_profile_image, size:'100x100' %><br>
                <%= book.user.name %>
                <% end %>
              </td>
              <td><%= link_to book.title,book %></td>
              <td><%= book.body %></td>
              <td class="favorite_btn_<%= book.id %>">
                <%= render "favorites/favorite-btn", book: book %>
              </td>
              <td>コメント数：<%= book.book_comments.count %></td>
              <td>閲覧数：<%= book.read_counts.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

bookers2_789a/app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
            <td class="favorite_btn_<%= @book.id %>">
              <%= render "favorites/favorite-btn", book: @book %>
            </td>
          <td><td>閲覧数：<%= @book.read_counts.count %></td></td>
          <td>コメント数：<%= @book.book_comments.count %></td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy',book_path(@book) , method: :delete,
                    data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
        </tr>
      </table>
      <div class="m-2">
        <% @book.book_comments.each do |book_comment| %>
          <%= link_to image_tag book_comment.user.get_profile_image, size:"60x60", class:"my-2 mr-2" %>
            <%= book_comment.comment %>

            <% if book_comment.user == current_user %>
              <%= link_to "Destroy", book_book_comment_path(book_comment.book,book_comment),
                  method: :delete, data: { confirm: '本当に消しますか？' },class: "btn btn-danger mx-3" %><br>
            <% end %>
            <%= link_to book_comment.user.name , user_path(book_comment.user_id) %><br>
        <% end %>
      </div>

      <div class="form-group">
        <%= form_with model:[@book,@book_comment] do |f| %>
          <%= f.text_area:comment,rows:'5',class:"form-control" %><br>
          <%= f.submit"Post",class:"btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

bookers2_789a/app/views/rooms/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-lg-6 mx-auto">
      <div class="">
        <% @entries.each do |e| %>
          <% if current_user.id != e.user.id %>
            <h2 class="my-3"><%= e.user.name %>さんとのトークルーム</h2>
          <% end %>
        <% end %>
        <%= link_to "ユーザー一覧に戻る", users_path %><br>

        <% if @messages != nil %>
          <% @messages.each do |m| %>
            <%= m.user.name %>
            <%= m.message %><br>
          <% end %>
        <% else %>
          <p>まだメッセージはありません</p>
        <% end %>

        <%= form_with model: @message do |f| %>
          <%= f.text_area :message, placeholder: "メッセージはここに" , size: 50, class:"form-control mt-5" %>
          <%= f.hidden_field :room_id, value: @room.id %><br>
          <%= f.submit "post", class:"btn btn-info form-control" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

bookers2_789a/app/views/users/_dm_btn.html.erb
<% unless @user.id == curent_user.id %>
  <% if (current_user.following? @user) && (@user.following? current_user) %>
    <% if @isRoom == true %>
      <p class="user-show-room"><a href="/rooms/<%= @roomId %>" class="btn btn-primary btn-lg">チャットへ</a></p>
    <% else %>
      <%= form_with model: @room do |f| %>
        <%= fields_for @entry do |e| %>
          <%= e.hidden_field :user_id, value: @user.id %>
        <% end %>
        <%= f.submit "チャットを始める", class:"btn btn-primary btn-lg user-show-chat" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

bookers2_789a/app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user.id) %></th>
  </tr>
</table>

<div class='row'>
  <% if user == current_user %>
    <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% else %>
    <% if current_user.following?(user) %>
      <%= link_to 'Unfollow', user_relationships_path(user.id),class:"btn btn-info ml-3", method: :delete %>
    <% else %>
      <%= link_to 'Follow', user_relationships_path(user.id),class:"btn btn-success ml-3", method: :post %>
    <% end %>

    <% if (current_user.following? user) && (user.following? current_user) %>
      <% if @isRoom == true %>
        <p class="user-show-room"><a href="/rooms/<%= @roomId %>" class="btn btn-primary">チャットへ</a></p>
      <% else %>
        <%= form_with model: @room do |f| %>
          <%= fields_for @entry do |e| %>
            <%= e.hidden_field :user_id, value: user.id %>
          <% end %>
          <%= f.submit "チャットを始める", class:"btn btn-primary ml-2 user-show-chat" %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>


</div>

bookers2_789a/app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="4"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to(book.user) do %>
                <%= image_tag book.user.get_profile_image, size:'100x100' %><br>
                <%= book.user.name %>
                <% end %>
              </td>
              <td><%= link_to book.title,book %></td>
              <td><%= book.body %></td>
              <td class="favorite_btn_<%= book.id %>">
                <%= render "favorites/favorite-btn", book: book %>
              </td>
              <td>コメント数：<%= book.book_comments.count %></td>
              <td>閲覧数：<%= book.read_counts.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>