bookers2_789b/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "homes#top"
  get "home/about"=>"homes#about"

  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites,only: [:create,:destroy]
    resources :book_comments, only: [:create,:destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships,only: [:create,:destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'search_count' => 'users#search_count'
  end
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/search' => 'searches#search'

end

bookers2_789b/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorite, dependent: :destroy

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorite.exists?(user_id: user.id)
  end

  def self.looks(search,word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?", "#{word}")
    elsif search == "forword_match"
      @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?", "%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?", "%#{word}%")
    else
      @book = Book.all
    end
  end

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.days.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

  scope :created_each_date, -> (date){ where(created_at: date.days.ago.all_day) }
  def self.book_week_count
    (1..6).map { |date| created_each_date(date).count}.reverse
  end

end

bookers2_789b/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :name, presence: true
  validates :introduction, length: { maximum: 50 }



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.looks(search,word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end
end

bookers2_789b/app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search],params[:word])
    else
      @books = Book.looks(params[:search],params[:word])
    end
    render "/layouts/search_result"
  end
  
  
end

bookers2_789b/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update,:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new

    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week

    @the_day_before = @today_book.count / @yesterday_book.count.to_f
    @the_week_before = @this_week_book.count / @last_week_book.count.to_f
  end



  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def search_count
    @user = User.find(params[:user_id])
    if params[:created_at] == nil
      @books == "日付を入力してください"
    else
      @books = @user.books.where(created_at: params[:created_at].to_date.all_day)
      render :search_count
    end
  end



  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

bookers2_789b/app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"60x60" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
            <td>
              <% if @book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(@book),class:"text-danger", method: :delete do %>
                  <i class="fas fa-heart"></i><%= @book.favorite.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(@book),class:"text-primary", method: :post do %>
                  <i class="fas fa-heart"></i><%= @book.favorite.count %>
                <% end %>
              <% end %>
            </td>
          <td>コメント数：<%= @book.book_comments.count %></td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy',book_path(@book) , method: :delete,
                    data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
        </tr>
      </table>
      <div class="m-2">
        <% @book.book_comments.each do |book_comment| %>
          <%= link_to image_tag book_comment.user.get_profile_image, size:"60x60", class:"my-2 mr-2" %>
            <%= book_comment.comment %>

            <% if book_comment.user == current_user %>
              <%= link_to "Destroy", book_book_comment_path(book_comment.book,book_comment),
                  method: :delete, data: { confirm: '本当に消しますか？' },class: "btn btn-danger mx-3" %><br>
            <% end %>
            <%= link_to book_comment.user.name , user_path(book_comment.user_id) %><br>
        <% end %>
      </div>

      <div class="form-group">
        <%= form_with model:[@book,@book_comment] do |f| %>
          <%= f.text_area:comment,rows:'5',class:"form-control" %><br>
          <%= f.submit"Post",class:"btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

bookers2_789b/app/views/users/_chart.html.erb
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<canvas id="myChart"></canvas>
  <script>
    $(document).on('turbolinks:load', function(){
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx,{
        type: 'line',
        data: {
          labels: ['６日前', '５日前', '４日前', '３日前', '２日前', '昨日', '今日'],
          datasets: [
            {
              label: '投稿した本の数',
              data: [
                <%= books.created_each_date(6).count %>,
                <%= books.created_each_date(5).count %>,
                <%= books.created_each_date(4).count %>,
                <%= books.created_each_date(3).count %>,
                <%= books.created_each_date(2).count %>,
                <%= books.created_each_date(1).count %>,
                <%= books.created_each_date(0).count %>

              ],
              borderColor: "rgba(0,0,255,1)",
              backgroundColor: "rgba(0,0,0,0)",
              tension: 0.4
            }
          ],
        },
        options: {
          title: {
            display: true,
            text: '７日間の投稿数の比較'
          },
          responsive: true,
          scales: {
            y:{
              suggestedMin: 0,
              suggestedMax: 10
            },
            x:{
              stacked: true
            },
          },
        }
      });
    });
  </script>

bookers2_789b/app/views/users/_post_count.html.erb
<table class="table my-2">
  <tr>
    <th>今日の投稿数</th>
    <th></th>
    <th>前日の投稿数</th>
    <th></th>
    <th>前日比</th>
  </tr>
  <tr>
    <td><%= today_book.count %></td>
    <td></td>
    <td><%= yesterday_book.count %></td>
    <td></td>
    <td>
      <% if yesterday_book.count == 0 %>
        前日の投稿はなし
      <% else %>
        <%= (the_day_before * 100).round %>%
      <% end %>
    </td>
  </tr>
</table>
<table class="table">
  <tr>
    <th>今週の投稿数</th>
    <th></th>
    <th>前週の投稿数</th>
    <th></th>
    <th>前週比</th>
  </tr>
  <tr>
    <td><%= this_week_book.count %></td>
    <td></td>
    <td><%= last_week_book.count %></td>
    <td></td>
    <td>
      <% if last_week_book.count == 0 %>
        前週の投稿はなし
      <% else %>
        <%= (the_week_before * 100).round %>%
      <% end %>
    </td>
  </tr>
</table>
<h4>7日間分の投稿数</h4>
<table class="table table-bordered text-center">
  <tr>
    <th>６日前</th>
    <th>５日前</th>
    <th>４日前</th>
    <th>３日前</th>
    <th>２日前</th>
    <th>１日前</th>
    <th>今日</th>
  </tr>
  <tr>
    <% books.book_week_count.each do |c| %>
      <th><%= c %></th>
    <% end %>
    <th><%= today_book.count %></th>
  </tr>
</table>

bookers2_789b/app/views/users/_search_count.html.erb
<div class='col-md-5'>
  <%= form_with url: user_search_count_path(user), method: :get, class: "row justify-content-center", local: false do |f| %>
    <div class="col-auto">
      <%= f.date_field :created_at, class: "form-control" %>
    </div>
    <div class="col-auto">
      <%= f.submit "検索" , class: "btn btn-primary"%>
    </div>
  <% end %>
</div>
<div class="search_result">
</div>

bookers2_789b/app/views/users/search_count.js.erb
$('.search_result').html(`
  <h2>検索結果</h2>
  <div class="card" >
    <div class="card-header">投稿数</div>
    <div class="card-body">
      <%= j( @books.count ) %>
    </div>
  </div>
`)

bookers2_789b/app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to(book.user) do %>
                <%= image_tag book.user.get_profile_image, size:'60x60' %><br>
                <%= book.user.name %>
                <% end %>
              </td>
              <td><%= link_to book.title,book %></td>
              <td><%= book.body %></td>
              <td class="favorite_btn_<%= book.id %>">
                <%= render "favorites/favorite-btn", book: book %>
              </td>
              <td>コメント数：<%= book.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= render 'post_count', books: @books, today_book: @today_book, yesterday_book: @yesterday_book, this_week_book: @this_week_book, the_day_before: @the_day_before, last_week_book: @last_week_book %>
      <%= render 'chart', books: @books, today_book: @today_book %>
      <%= render 'search_count', user: @user %>
    </div>
  </div>
</div>